modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="tutorial"
displayName="Tutorial Mod"
version="${file.jarVersion}"
logoFile="icon.png"
authors="noja299792458"
description='''
 Tutorial Mod for Forge
'''

[[dependencies.tutorial]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.tutorial]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
